MyStorage/Controllers/Api/CategoriesController.cs
using AutoMapper;
using MyStorage.Core;
using MyStorage.Core.Dtos.Category;
using MyStorage.Core.Models;
using System.Linq;
using System.Web.Http;

namespace MyStorage.Controllers.Api
{
    [Authorize]
    public class CategoriesController : ApiController
    {        
        private readonly IUnitOfWork _unitOfWork;

        public CategoriesController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }        

        //GET: /Api/Categories
        [AllowAnonymous]
        public IHttpActionResult GetCategories()
        {
            var categoryDtos = _unitOfWork.Categories
                .GetCategories()
                .Select(Mapper.Map<Category, CategoryDto>);                

            return Ok(categoryDtos);
        }
    }
}

MyStorage/Controllers/CategoriesController.cs
using MyStorage.Core;
using MyStorage.Core.Models;
using MyStorage.Core.ViewModels;
using System.Data.Entity.Core;
using System.Web.Mvc;

namespace MyStorage.Controllers
{
    [Authorize]
    public class CategoriesController : Controller
    {        
        private readonly IUnitOfWork _unitOfWork;

        public CategoriesController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;            
        }        

        public ActionResult ListCategoryTypes(int id)
        {
            var category = _unitOfWork.Categories.GetCategoryWithTypes(id);

            if (category == null)
                return HttpNotFound();

            return View(category);
        }


        public ActionResult Index()
        {
            var categories = _unitOfWork.Categories.GetCategories();

            return View(categories);
        }


        public ActionResult Create()
        {
            return View("CategoryForm", new CategoryFormViewModel());
        }

        public ActionResult Edit(int id)
        {
            var category = _unitOfWork.Categories.GetCategoryWithTypes(id);

            if (category == null)
                return HttpNotFound();

            return View("CategoryForm", new CategoryFormViewModel(category));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Save(CategoryFormViewModel viewModel)
        {
            if (!ModelState.IsValid)
                return View("CategoryForm", viewModel);

            if (IsAddingNewCategory(viewModel))
            {
                AddNewCategory(viewModel);
            }
            else
            {
                UpdateCategory(viewModel);
            }

            return RedirectToAction("Index", "Categories");
        }

        private void UpdateCategory(CategoryFormViewModel viewModel)
        {
            var category = _unitOfWork.Categories.GetCategoryWithTypes(viewModel.Id);

            if (category == null)
                throw new ObjectNotFoundException();

            category.Name = viewModel.Name;
            _unitOfWork.Complete();
        }

        private void AddNewCategory(CategoryFormViewModel viewModel)
        {
            var newCategory = new Category
            {
                Name = viewModel.Name
            };

            _unitOfWork.Categories.Add(newCategory);
            _unitOfWork.Complete();
        }

        private bool IsAddingNewCategory(CategoryFormViewModel viewModel)
        {
            return viewModel.Id == 0;
        }
    }
}

MyStorage/Controllers/CategoryTypesController.cs
using MyStorage.Core;
using MyStorage.Core.Models;
using MyStorage.Core.ViewModels;
using System.Data.Entity.Core;
using System.Web.Mvc;

namespace MyStorage.Controllers
{
    [Authorize]
    public class CategoryTypesController : Controller
    {        
        private readonly IUnitOfWork _unitOfWork;

        public CategoryTypesController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }        

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(int categoryId)
        {
            var viewModel = new CategoryTypeViewModel
            {
                CategoryId = categoryId
            };

            return View("CategoryTypeForm", viewModel);
        }

        public ActionResult Edit(int id)
        {
            var categoryType = _unitOfWork.CategoryTypes.GetCategoryType(id);

            if (categoryType == null)
                return HttpNotFound();

            var viewModel = new CategoryTypeViewModel(categoryType);

            return View("CategoryTypeForm", viewModel);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Save(CategoryTypeViewModel viewModel)
        {
            if (!ModelState.IsValid)
                return View("CategoryTypeForm", viewModel);

            if (IsAddingNewCategoryType(viewModel))
            {
                AddNewCategoryType(viewModel);
            }
            else
            {
                UpdateCategoryType(viewModel);
            }

            _unitOfWork.Complete();
            return RedirectToAction("ListCategoryTypes", "Categories", new { id = viewModel.CategoryId });
        }

        private void UpdateCategoryType(CategoryTypeViewModel viewModel)
        {
            var categoryType = _unitOfWork.CategoryTypes.GetCategoryType(viewModel.Id);

            if (categoryType == null)
                throw new ObjectNotFoundException();

            categoryType.Name = viewModel.Name;
            _unitOfWork.Complete();
        }

        private void AddNewCategoryType(CategoryTypeViewModel viewModel)
        {
            var categoryType = new CategoryType
            {
                Name = viewModel.Name,
                CategoryId = viewModel.CategoryId
            };

            _unitOfWork.CategoryTypes.Add(categoryType);
            _unitOfWork.Complete();
        }

        private bool IsAddingNewCategoryType(CategoryTypeViewModel viewModel)
        {
            return viewModel.Id == 0;
        }
    }
}

MyStorage/Views/Categories/CategoryForm.cshtml
@model MyStorage.Core.ViewModels.CategoryFormViewModel

@{
    ViewBag.Title = "CategoryForm";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (Model.Id == 0)
{
    <h2>Add New Category</h2>
}
else
{
    <h2>Update Category</h2>
}

@using (Html.BeginForm("Save", "Categories"))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(c => c.Id)
    <div class="form-group">
        @Html.LabelFor(c => c.Name, new { @class = "control-label" })
        @Html.TextBoxFor(c => c.Name, new { @class = "form-control" })
        @Html.ValidationMessageFor(c => c.Name)
    </div>

    <button type="submit" class="btn btn-primary btn-lg">Submit</button>
}

MyStorage/Views/Categories/Index.cshtml
@model IEnumerable<MyStorage.Core.Models.Category>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>List of Categories</h2>

<p>
    @Html.ActionLink("Add New Category", "Create", "Categories")
</p>

<table id="category-table" class="table table-hover table-striped table-bordered">
    <thead>
        <tr>
            <th>Code</th>
            <th>Category Name</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var category in Model)
        {
            <tr>
                <td class="text-middle">@category.Id</td>
                <td class="text-middle">@category.Name @String.Format("({0})", category.CategoryTypes.Count)</td>
            <td>
                <a class="btn btn-primary btn-sm" href="@Url.Action("Edit", "Categories", new {id = category.Id})">
                    <span class="glyphicon glyphicon-pencil"></span>
                    Edit
                </a>
                <a class="btn btn-info btn-sm" href="@Url.Action("ListCategoryTypes", "Categories", new { id = category.Id })">
                    <span class="glyphicon glyphicon-list"></span>
                    List Types
                </a>
                <a class="btn btn-danger btn-sm" href="#">
                    <span class="glyphicon glyphicon-trash"></span>
                    Remove
                </a>
            </td>
        </tr>
        }
    </tbody>
</table>

@section scripts
{
    <script>
        $(document).ready(function () {
            $("#category-table").DataTable();
        });
    </script>
}

MyStorage/Views/Categories/ListCategoryTypes.cshtml
@model MyStorage.Core.Models.Category

@{
    ViewBag.Title = "List Category Types";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@Model.Name Types</h2>

<p>
    @using (Html.BeginForm("Create", "CategoryTypes"))
    {
        @Html.AntiForgeryToken()
        @Html.Hidden("categoryId", Model.Id)
        <button type="submit" class="btn btn-link">Add New Type</button>
    }
</p>

<table id="category-type-table" class="table table-hover table-striped table-bordered">
    <thead>
        <tr>
            <th>Code</th>
            <th>Type Name</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var type in Model.CategoryTypes)
        {
            <tr>
                <td class="text-middle">@type.Id</td>
                <td class="text-middle">@type.Name</td>
                <td>
                    <a class="btn btn-primary btn-sm" href="@Url.Action("Edit", "CategoryTypes", new {id = type.Id})">
                        <span class="glyphicon glyphicon-pencil"></span>
                        Edit
                    </a>
                    <a class="btn btn-danger btn-sm" href="#">
                        <span class="glyphicon glyphicon-trash"></span>
                        Remove
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>

@section scripts
{
    <script>
        $(document).ready(function () {
            $("#category-type-table").DataTable();
        });
    </script>
}